name: CI

on: 
  push:
    branches:
      - master

jobs: 
    runs-on: ubuntu-latest
    steps:
    - name: API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "Using API Key: $API_KEY"
